# This is a basic workflow to help you get started with Actions

name: ContinuousIntegration

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" , "ContinuousIntegration"]
  pull_request:
    branches: [ "main" , "ContinuousIntegration"]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Test and Package (maven)
        run: mvn -B -e -T 1C -P prod clean package
        
      - name: Build Docker image
        run: docker build -t ${{ secrets.REGISTRY_USER }}/mutant-detector:latest .

      - name: Login to Docker registry
        run: echo ${{ secrets.REGISTRY_PASS }} | docker login -u ${{ secrets.REGISTRY_USER }} --password-stdin
      
      - name: Push image
        run: docker push ${{ secrets.REGISTRY_USER }}/mutant-detector:latest
